test:
    host: localhost
    port: 5432
    user: postgres
    dbname: test
    sslmode: disable
    statementTimeout: "1s"
    workers: 5
    labels:
        datname: "test"
    queryFiles:
        - "basic.yaml":
            labels:
                l1: "v1"
                l2: "v2"
        - "pgsettings.yaml":
            labels:
                label1: "value1"
                label2: "value2"
